//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThreatModellingGame.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AllText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AllText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ThreatModellingGame.Web.Resources.AllText", typeof(AllText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Threat Modelling Card Game.
        /// </summary>
        public static string App_SubTitle {
            get {
                return ResourceManager.GetString("App_SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation of Privilege (EoP).
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Name.
        /// </summary>
        public static string Change_Name {
            get {
                return ResourceManager.GetString("Change_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the name under which you would like to appear to other players..
        /// </summary>
        public static string Change_Username_Info {
            get {
                return ResourceManager.GetString("Change_Username_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a user name.
        /// </summary>
        public static string Change_Username_Label {
            get {
                return ResourceManager.GetString("Change_Username_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your name.
        /// </summary>
        public static string Change_Username_Link {
            get {
                return ResourceManager.GetString("Change_Username_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to change your name?.
        /// </summary>
        public static string Change_Username_Title {
            get {
                return ResourceManager.GetString("Change_Username_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create new Game.
        /// </summary>
        public static string Create_New_Game {
            get {
                return ResourceManager.GetString("Create_New_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string Credits {
            get {
                return ResourceManager.GetString("Credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string Game {
            get {
                return ResourceManager.GetString("Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game originally invented by Microsoft.
        /// </summary>
        public static string Game_Invented_By_Microsoft {
            get {
                return ResourceManager.GetString("Game_Invented_By_Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games currently playing.
        /// </summary>
        public static string Games_Currently_Playing {
            get {
                return ResourceManager.GetString("Games_Currently_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started.
        /// </summary>
        public static string Get_Started {
            get {
                return ResourceManager.GetString("Get_Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information please visit the.
        /// </summary>
        public static string Home_Index_GitHub_Reference {
            get {
                return ResourceManager.GetString("Home_Index_GitHub_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the first beta version of the.
        /// </summary>
        public static string Home_Index_Intro {
            get {
                return ResourceManager.GetString("Home_Index_Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome fellow security enthusiast.
        /// </summary>
        public static string Home_Index_Welcome {
            get {
                return ResourceManager.GetString("Home_Index_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        public static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Game.
        /// </summary>
        public static string Join_Game {
            get {
                return ResourceManager.GetString("Join_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please pick a name for the new game..
        /// </summary>
        public static string Missing_Game_Name_Error {
            get {
                return ResourceManager.GetString("Missing_Game_Name_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name..
        /// </summary>
        public static string Missing_Username_Error {
            get {
                return ResourceManager.GetString("Missing_Username_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string New_Game {
            get {
                return ResourceManager.GetString("New_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To get started you simply pick a name and afterwards you will be taken straight to the game from where you can share the game URL and invite your team members..
        /// </summary>
        public static string New_Game_Info {
            get {
                return ResourceManager.GetString("New_Game_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a game name.
        /// </summary>
        public static string New_Game_Label {
            get {
                return ResourceManager.GetString("New_Game_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not participating in any games at the moment..
        /// </summary>
        public static string Not_Playing_Any_Games {
            get {
                return ResourceManager.GetString("Not_Playing_Any_Games", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Players.
        /// </summary>
        public static string Players {
            get {
                return ResourceManager.GetString("Players", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online version powered by.
        /// </summary>
        public static string Powered_By {
            get {
                return ResourceManager.GetString("Powered_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before you can start playing you need to pick a user name! Under which name would you like to show up to other players?.
        /// </summary>
        public static string Register_Info {
            get {
                return ResourceManager.GetString("Register_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New to the game?.
        /// </summary>
        public static string Register_Title {
            get {
                return ResourceManager.GetString("Register_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start playing.
        /// </summary>
        public static string Start_Playing {
            get {
                return ResourceManager.GetString("Start_Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string URL {
            get {
                return ResourceManager.GetString("URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share this URL with your team mates. They can join the game by copy pasting it into the browser. IMPORTANT: After a new user joins the game all other users need to refresh their browser to pick up the changes. This will be changed in an upcoming version..
        /// </summary>
        public static string URL_Share_Info {
            get {
                return ResourceManager.GetString("URL_Share_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to join the game.
        /// </summary>
        public static string Want_To_Join_Game {
            get {
                return ResourceManager.GetString("Want_To_Join_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Details.
        /// </summary>
        public static string Your_Details {
            get {
                return ResourceManager.GetString("Your_Details", resourceCulture);
            }
        }
    }
}
